# .pre-commit-config.yaml
repos:
    - repo: https://github.com/psf/black
      rev: 24.3.0
      hooks:
          - id: black
            language_version: python3.12

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.4.1
      hooks:
          - id: ruff
            args: ["--fix"]
            language_version: python3.12

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.0
      hooks:
          - id: mypy
            additional_dependencies: []
            language_version: python3.12

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-yaml
          - id: check-added-large-files
